[tool.poetry]
name = "ignition-stack/hello-world"
version = "0.1.0"
description = "Ignition stack - hello world"
authors = ["jshimazu"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"